DATASET:
  TRAIN: "D:/data_03_10/dataset/train.txt"
  VAL: "D:/data_03_10/dataset/val.txt"
  NAMES: "configs/coco.names"
MODEL:
  NC: 80
  INPUT_WIDTH: 352
  INPUT_HEIGHT: 352
TRAIN:
  LR: 0.001
  THRESH: 0.25
  WARMUP: true
  BATCH_SIZE: 96
  END_EPOCH: 300
  MILESTIONES:
    - 100
    - 200
    - 250