DATASET:
  TRAIN: "C:/ZWZ/ROBOCON/FastestDet/dataset/train.txt"
  VAL: "C:/ZWZ/ROBOCON/FastestDet/dataset/val.txt"
  NAMES: "C:/ZWZ/ROBOCON/FastestDet/dataset/category.names"
  ANCHOR_SIZES:
    [[0.07711985, 0.10994485],
     [0.12846589, 0.21537308],
     [0.19778088, 0.31619958],
     [0.23630117, 0.48031218]]
MODEL:
  NC: 4
  INPUT_WIDTH: 352 #1024
  INPUT_HEIGHT: 352 #576
TRAIN:
  LR: 0.001
  THRESH: 0.25
  WARMUP: true
  BATCH_SIZE: 64
  END_EPOCH: 350
  MILESTIONES:
    - 100
    - 200
    - 280